In [2]:
import pandas as pd

reviews = pd.read_csv('02_data.csv')
reviews

,nome,idade,email,estado,genero_musical,linguagem
0,Samuel Melo,27,goncalvesdanilo@gmail.com,Espírito Santo,Blues,Python
1,Henrique da Mata,60,jesusisadora@uol.com.br,Rondônia,Jazz,Java
2,Luigi Cunha,39,acarvalho@uol.com.br,Minas Gerais,Hip Hop,Python
3,Dra. Fernanda Novaes,29,ribeiropietra@yahoo.com.br,Amazonas,Sertanejo,Java
4,Joaquim Ferreira,60,emelo@gmail.com,Distrito Federal,Eletrônica,Java
...,...,...,...,...,...,...
195,Vitor Gabriel da Cruz,32,jbarros@uol.com.br,Sergipe,Eletrônica,Python
196,Letícia Silveira,20,jsilveira@pereira.org,Rio Grande do Norte,Hip Hop,Python
197,Vitor Hugo Carvalho,65,rodriguesbreno@correia.br,Bahia,Pagode,Python
198,Davi Lucas Nogueira,56,ada-conceicao@uol.com.br,Minas Gerais,Rock,Java
199,Luiz Otávio Azevedo,43,maria-sophianogueira@lopes.net,Amapá,Funk,Java

In [4]:
# Uma função que temos usado intensamente até agora é a função value_counts ().
# Podemos replicar o que value_counts () faz fazendo o seguinte:
reviews.groupby('genero_musical').genero_musical.count()

genero_musical
Axé                 7
Blues              16
Country            12
Eletrônica         15
Forró               9
Funk               13
Gospel             13
Hip Hop            11
Jazz                8
MPB                15
Música clássica     7
Pagode              6
Pop                11
Rap                10
Reggae              9
Rock               14
Samba              11
Sertanejo          13
Name: genero_musical, dtype: int64

In [5]:
# faz a soma e mostra o dado predominando diente de outra coluna
reviews.groupby('genero_musical').estado.min()

genero_musical
Axé                           Ceará
Blues                          Acre
Country                     Alagoas
Eletrônica                     Acre
Forró                          Acre
Funk                           Acre
Gospel                         Acre
Hip Hop                       Ceará
Jazz                           Acre
MPB                            Acre
Música clássica             Alagoas
Pagode                        Bahia
Pop                            Acre
Rap                            Acre
Reggae             Distrito Federal
Rock                        Alagoas
Samba                         Amapá
Sertanejo                   Alagoas
Name: estado, dtype: object

In [10]:
reviews.groupby('genero_musical').estado.agg([len, min, max])

                 len               min                max
genero_musical
Axé                7             Ceará          São Paulo
Blues             16              Acre           Rondônia
Country           12           Alagoas          Tocantins
Eletrônica        15              Acre          Tocantins
Forró              9              Acre  Rio Grande do Sul
Funk              13              Acre          Tocantins
Gospel            13              Acre          Tocantins
Hip Hop           11             Ceará           Rondônia
Jazz               8              Acre     Santa Catarina
MPB               15              Acre          Tocantins
Música clássica    7           Alagoas       Minas Gerais
Pagode             6             Bahia            Roraima
Pop               11              Acre          Tocantins
Rap               10              Acre          Tocantins
Reggae             9  Distrito Federal     Santa Catarina
Rock              14           Alagoas          São Paulo
Samba             11             Amapá          Tocantins
Sertanejo         13           Alagoas     Santa Catarina

In [29]:
genero_estado = reviews.groupby(['estado', 'genero_musical']).linguagem.agg([len])
genero_estado.to_csv('genero_estado.csv')

In [32]:
# exibe todos os indeces
reviews.index

RangeIndex(start=0, stop=200, step=1)

In [34]:
# cria um novo index
reviews.reset_index()

,index,nome,idade,email,estado,genero_musical,linguagem
0,0,Samuel Melo,27,goncalvesdanilo@gmail.com,Espírito Santo,Blues,Python
1,1,Henrique da Mata,60,jesusisadora@uol.com.br,Rondônia,Jazz,Java
2,2,Luigi Cunha,39,acarvalho@uol.com.br,Minas Gerais,Hip Hop,Python
3,3,Dra. Fernanda Novaes,29,ribeiropietra@yahoo.com.br,Amazonas,Sertanejo,Java
4,4,Joaquim Ferreira,60,emelo@gmail.com,Distrito Federal,Eletrônica,Java
...,...,...,...,...,...,...,...
195,195,Vitor Gabriel da Cruz,32,jbarros@uol.com.br,Sergipe,Eletrônica,Python
196,196,Letícia Silveira,20,jsilveira@pereira.org,Rio Grande do Norte,Hip Hop,Python
197,197,Vitor Hugo Carvalho,65,rodriguesbreno@correia.br,Bahia,Pagode,Python
198,198,Davi Lucas Nogueira,56,ada-conceicao@uol.com.br,Minas Gerais,Rock,Java
199,199,Luiz Otávio Azevedo,43,maria-sophianogueira@lopes.net,Amapá,Funk,Java

In [36]:
# ordena (ascending=False) para orde
reviews.sort_values(by='idade')

,nome,idade,email,estado,genero_musical,linguagem
185,Clara da Mata,18,mariane89@silva.br,Rio de Janeiro,Rap,Python
100,Joaquim Rezende,18,joao-pedroaragao@yahoo.com.br,Alagoas,Rock,Python
30,Melissa Costela,18,vbarbosa@pereira.com,Espírito Santo,Rock,Java
135,Dr. Caio Lima,18,ccaldeira@hotmail.com,Santa Catarina,Pop,Java
168,Julia Fernandes,18,teixeiramaria-cecilia@rezende.br,Paraná,Country,Java
...,...,...,...,...,...,...
68,Ana Luiza da Luz,69,nunesisis@da.br,Espírito Santo,Samba,Java
182,Maria Cecília Gonçalves,69,da-cunhaluigi@bol.com.br,Distrito Federal,Funk,Python
159,Carlos Eduardo Fernandes,69,catarina31@bol.com.br,Alagoas,Country,Java
114,Luna Fogaça,70,pietra45@gmail.com,Tocantins,Funk,Python
178,Ian Duarte,70,arthur31@ig.com.br,Espírito Santo,MPB,Python